name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: ShellCheck
      run: |
        sudo apt-get install shellcheck -y
        shellcheck -s bash -e SC2154 -e SC1090 -e SC1017 gestionestandgastronomico.sh
    - name: Setup PlayOnLinux_Tools script checker
      run: |
        git clone https://github.com/PlayOnLinux/PlayOnLinux_Tools
        source PlayOnLinux_Tools/PlayOnLinux_ScriptChecker/script_checker.sh gestionestandgastronomico.sh
