name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup ShellCheck
      run: |
        wget https://github.com/koalaman/shellcheck/releases/download/stable/shellcheck-stable.linux.x86_64.tar.xz
        tar xf shellcheck-stable.linux.x86_64.tar.xz
        chmod +x shellcheck-stable/shellcheck
        shellcheck-stable/shellcheck -V
    - name: ShellCheck
      run: shellcheck-stable/shellcheck -s bash -e SC2154 -e SC1090 -e SC1017 gestionestandgastronomico.sh
    - name: Setup PlayOnLinux_Tools script checker
      run: |
        git clone https://github.com/PlayOnLinux/PlayOnLinux_Tools
        cd PlayOnLinux_Tools/PlayOnLinux_ScriptChecker
        sed -i 's/\r//' ../../gestionestandgastronomico.sh
        source script_checker.sh ../../gestionestandgastronomico.sh
