name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup ShellCheck
      run: |
        wget https://github.com/koalaman/shellcheck/releases/download/stable/shellcheck-stable.linux.x86_64.tar.xz
        tar xf shellcheck-stable.linux.x86_64.tar.xz
        sudo mv shellcheck-stable/shellcheck /usr/bin/shellcheck
        chmod +x /usr/bin/shellcheck
        shellcheck -V
    - name: Run script checker
      run: |
        wget https://gist.github.com/MatteoGheza/7227474476a2a008922aa958f881be15/raw/b9114529c139dd3fd258016ae246565a7026f377/script_checker.sh
        chmod +x script_checker.sh
        sed -i 's/\r//' gestionestandgastronomico.sh
        ./script_checker.sh gestionestandgastronomico.sh
